---
- hosts: dev
  become: yes
  remote_user: ec2-user
  
- tasks:
    - name: Install Apache
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - php
        - php-mysql

    - name: Download Wordpress
      get_url:
        url: "http://wordpress.org/wordpress-latest.tar.gz"
        dest: "/var/www/html/wordpress.tar.gz"
      force: yes

    - name: Extract Wordpress
      command: "tar xvf /var/www/html/wordpress.tar.gz \
        -C /var/www/htmp --strip-components 1"
       
    - name: Make my directory treee readable
      file:
        path: /var/www/html
        mode: u=rwX,g=rX,o=rX
        recurse:  yes
        owner: apache
        owner: apache

    - name: Make sure Apache is started now andat boot
      service:
        name: httpd
        state: started
        enabled: yes 
